### ISSUE TITLE
Is it possible to use concordex directly from python? An example in readme would help

### ISSUE THREAD

**Issue by vitkl** [pachterlab/concordex#1]
Hi

Congratulations and looking forward to using concordex. Is it possible to use concordex directly from python as opposed to command-line? An example in the readme would help a lot with uptake of the method.

**Comment by sbooeshaghi** [comment]
Yes. We will add a description of how to do so soon. Thank you for the suggestion!

**Comment by sbooeshaghi** [comment]
Ok I wrote up a short code snippet in the README- lmk how it works.
