### ISSUE TITLE
Example of Inputs 

### ISSUE THREAD

**Issue by IsaacDiaz026** [pachterlab/concordex#2]
Hello, I was wondering if you could elaborate on the inputs for this tool? Do you have any example files?

**Comment by kayla-jackson** [comment]
Hi @IsaacDiaz026 

Here is a link to some [example data](https://caltech.box.com/s/uoay3zywsp2dor2pl4xs1cqee3wz63k4). 

Both `concordex_map` and `concordex_stat` accept a sparse count matrix and cell assignments as input. Assignments can be any discrete label (e.g. batch, cell type). If you're running concordex from the command line, assignments are provided as a text file with one assignment per line, and the count matrix is a mtx file (i.e. the output of `scipy.io.mmwrite(...)`). The order of the assignments in the assignments file should match the order of the cells in the count matrix. 

We'll be updating the documentation, but please reach out with any additional questions.

**Comment by IsaacDiaz026** [comment]
Thank you ! @kayla-jackson
