### ISSUE TITLE
Has this been used for scATAC-seq before? 

### ISSUE THREAD

**Issue by IsaacDiaz026** [pachterlab/concordex#3]

**Comment by kayla-jackson** [comment]
Hi @IsaacDiaz026, 

To my knowledge, concordex hasn't been used for scATAC-seq _yet_. Can you tell me a bit more about the goals of the analysis you are conducting? Perhaps I can provide a working example for your application. 

Thanks, 
KJ

**Comment by IsaacDiaz026** [comment]
Hi Kayla,

My goal is to cluster scATAC-seq and annotate cell-types using gene activity scores determined from the ATAC-seq data. I have used LSI for dimensionality reduction and used these embeddings for cell clustering. 

I would like to compare the results of clustering with different parameters, and figured the Concordex  ratio would be helpful for making these comparisons.

**Comment by kayla-jackson** [comment]
concordex can definitely be useful here. The necessary inputs are a nearest-neighbor graph (e.g. knn) and discrete labels. If I understand correctly, the nearest-neighbor graph is computed from the LSI embeddings and is fixed for any set of clustering parameters. Using concordex to compare clustering parameters will amount to simply changing the input labels that are derived from your clustering results.

It may also be interesting to generate a nearest-neighbor graph from the data before dimensionality reduction, cluster based on this graph, and compute concordex. Of course, this may be infeasible based on the dimensions of your particular data.
